import Foundation
import Testing
@testable import OTPBarCore

@Test func rfc6238All18Vectors() throws {
    // RFC 6238 Appendix B: expected values are published, not generated by our code.
    let times: [Double] = [59, 1111111109, 1111111111, 1234567890, 2000000000, 20000000000]
    let expected = [
        ["94287082", "07081804", "14050471", "89005924", "69279037", "65353130"],
        ["46119246", "68084774", "67062674", "91819424", "90698825", "77737706"],
        ["90693936", "25091201", "99943326", "93441116", "38618901", "47863826"]
    ]
    let seeds = try JSONDecoder().decode([String].self, from: fixture("rfc-seeds"))
    for (index, algorithm) in OTPAlgorithm.allCases.enumerated() {
        let entry = try OTPEntry(name: "RFC", secret: seeds[index], algorithm: algorithm, digits: 8)
        for (timeIndex, timestamp) in times.enumerated() {
            let code = try TOTP.generate(for: entry, at: Date(timeIntervalSince1970: timestamp))
            #expect(code.value == expected[index][timeIndex])
            #expect(code.validUntil.timeIntervalSince1970 == (floor(timestamp / 30) + 1) * 30)
        }
    }
}

@Test func allSupportedParametersAgainstNodeOpenSSL() throws {
    struct Vector: Decodable {
        let algorithm: OTPAlgorithm
        let digits: Int
        let period: Int
        let timestamp: Double
        let code: String
    }
    let vectors = try JSONDecoder().decode([Vector].self, from: fixture("totp-matrix"))
    #expect(vectors.count == 288)
    for vector in vectors {
        let entry = try OTPEntry(name: "Matrix", secret: publicTestSecret, algorithm: vector.algorithm,
                                 digits: vector.digits, period: vector.period)
        let code = try TOTP.generate(for: entry, at: Date(timeIntervalSince1970: vector.timestamp))
        #expect(code.value == vector.code)
        #expect(code.value.count == vector.digits)
        #expect(code.validUntil.timeIntervalSince1970 > vector.timestamp)
    }
}

@Test func base32PublishedRfc4648Examples() throws {
    for (encoded, plaintext) in [("MY======", "f"), ("MZXQ====", "fo"), ("MZXW6===", "foo"),
                                 ("MZXW6YQ=", "foob"), ("MZXW6YTB", "fooba"), ("MZXW6YTBOI======", "foobar")] {
        #expect(try Base32.decode(Base32.canonical(encoded)) == Data(plaintext.utf8))
    }
    #expect(try Base32.canonical("mzxw 6ytb oi======\n") == "MZXW6YTBOI")
}

@Test(arguments: ["", "A", "ABC", "ABCDEF", "M1======", "M0======", "MY=", "MY=======", "MY======A", "MZ======", "密钥"])
func invalidBase32IsRejected(_ secret: String) {
    #expect(throws: OTPError.invalidSecret) { try OTPEntry(name: "Invalid", secret: secret) }
}

@Test func invalidParametersAndTimeAreRejected() throws {
    for digits in [0, 4, 9, Int.max] {
        #expect(throws: OTPError.invalidParameters) { try OTPEntry(name: "Invalid", secret: publicTestSecret, digits: digits) }
    }
    for period in [0, -30, 15, Int.max] {
        #expect(throws: OTPError.invalidParameters) { try OTPEntry(name: "Invalid", secret: publicTestSecret, period: period) }
    }
    #expect(throws: OTPError.invalidName) { try OTPEntry(name: " \n ", secret: publicTestSecret) }
    let entry = try OTPEntry(name: "Valid", secret: publicTestSecret)
    for timestamp in [-1, Double.nan, .infinity, .greatestFiniteMagnitude] {
        #expect(throws: OTPError.invalidTime) { try TOTP.generate(for: entry, at: Date(timeIntervalSince1970: timestamp)) }
    }
}
